# Generated by Django 5.0.3 on 2024-03-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meter_rest', '0003_alter_imagedata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
