# Generated by Django 5.0.3 on 2024-03-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meter_rest', '0004_imagedata_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='image',
            field=models.ImageField(upload_to='WFCR_user/images/'),
        ),
    ]
